### ISSUE TITLE
sing-box.service failed

### ISSUE THREAD

**Issue by AndyLin2020** [yonggekkk/sing-box-yg#1]
Sing-box状态：未启动，可尝试选择6重启，依旧如此建议卸载重装Sing-box

Sing-box启动不起来，以下是日志：

-0400 2023-11-01 02:07:28 INFO router: downloading geosite database
-0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
-0400 2023-11-01 02:07:28 INFO router: downloading geosite database
-0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
-0400 2023-11-01 02:07:28 INFO router: downloading geosite database
-0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
FATAL[0000] start service: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
sing-box.service: main process exited, code=exited, status=1/FAILURE
Unit sing-box.service entered failed state.
sing-box.service failed.

**Comment by yonggekkk** [comment]
什么VPS。居然还要给权限。

**Comment by AndyLin2020** [comment]
> 什么VPS。居然还要给权限。

racknerd，试过其他脚本可以正常运行

**Comment by yonggekkk** [comment]
> -0400 2023-11-01 02:07:28 INFO router: downloading geosite database
> -0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
> -0400 2023-11-01 02:07:28 INFO router: downloading geosite database
> -0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
> -0400 2023-11-01 02:07:28 INFO router: downloading geosite database
> -0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
> FATAL[0000] start service: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
> sing-box.service: main process exited, code=exited, status=1/FAILURE
> Unit sing-box.service entered failed state.
> sing-box.service failed.

etc/s-box下有geosite.db文件吗？

**Comment by neohob** [comment]
我也是，非 rn 机器

**Comment by neohob** [comment]
到/etc/s-box下 wget 了 geosite.db文件，还是这个错误

**Comment by yonggekkk** [comment]
你们谁，来个机器，@我，我来试试看

**Comment by yonggekkk** [comment]
> ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!

能正常运行吗？

**Comment by neohob** [comment]
直接运行  /etc/s-box/sing-box run -c /etc/s-box/sb.json 可以，脚本里面启动 service 不行

**Comment by yonggekkk** [comment]
> 错误ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!

错误ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!
这个错误问题不大，默认我给了个值，的确不支持geosite。。没事

**Comment by neohob** [comment]
谢谢，serivce 的问题能解决吗？

**Comment by yonggekkk** [comment]
> 直接运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json 可以（除了错误ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists! ），脚本里面启动 service 不行，还是那个db文件的原因没有权限

你试试，把sb.json文件中，把
"geoip":{
"download_url":"https://github.com/soffchen/sing-geoip/releases/latest/download/geoip.db",
"download_detour":"direct"
},
"geosite":{
"download_url":"https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db",
"download_detour":"direct"
},
这段删除，再试试

**Comment by yonggekkk** [comment]
> > 错误ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!
> 
> 错误ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists! 这个错误问题不大，默认我给了个值做替换，的确不支持geosite。。没事

**Comment by neohob** [comment]
刚才改错了，重装，又好了，之前重装没有用

**Comment by yonggekkk** [comment]
> 刚才改错了，重装，又好了，之前重装没有用

。。。

**Comment by neohob** [comment]
难道是某个时段什么服务不能用导致？楼主试试看能用了吗

**Comment by yonggekkk** [comment]
> 难道是某个时段什么服务不能用导致？楼主试试看能用了吗

出现这个问题，Sing-box状态：未启动，可尝试选择6重启，依旧如此建议卸载重装Sing-box
你是这个表现？

**Comment by neohob** [comment]
> > 难道是某个时段什么服务不能用导致？楼主试试看能用了吗
> 
> 出现这个问题，Sing-box状态：未启动，可尝试选择6重启，依旧如此建议卸载重装Sing-box 你是这个表现？


是这个表现，和楼主一样，日志出错问题也基本一样

**Comment by yonggekkk** [comment]
> > > 难道是某个时段什么服务不能用导致？楼主试试看能用了吗
> > 
> > 
> > 出现这个问题，Sing-box状态：未启动，可尝试选择6重启，依旧如此建议卸载重装Sing-box 你是这个表现？
> 
> 是这个表现，和楼主一样，日志出错问题也基本一样

上楼说的，删除那段看看

**Comment by AndyLin2020** [comment]
> 直接运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json

删除了后重启还是一样错误，运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json 后就可正常运行
ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!

**Comment by yonggekkk** [comment]
> > 直接运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json
> 
> 删除了后重启还是一样错误，运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json 后就可正常运行 ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!

failed to initialize geosite: read geosite: code yg_kkk not exists!这个报错无所谓。关键是SB运行状态是运行中吗

**Comment by AndyLin2020** [comment]
> > > 直接运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json
> > 
> > 
> > 删除了后重启还是一样错误，运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json 后就可正常运行 ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!
> 
> failed to initialize geosite: read geosite: code yg_kkk not exists!这个报错无所谓。关键是SB运行状态是运行中吗

是的，状态是运行中

**Comment by yonggekkk** [comment]
> > > > 直接运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json
> > > 
> > > 
> > > 删除了后重启还是一样错误，运行 /etc/s-box/sing-box run -c /etc/s-box/sb.json 后就可正常运行 ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!
> > 
> > 
> > failed to initialize geosite: read geosite: code yg_kkk not exists!这个报错无所谓。关键是SB运行状态是运行中吗
> 
> 是的，状态是运行中

那就没事。。试下节点通不通

**Comment by yzx1208** [comment]
racknerd 报错
请输入数字:10
退出日志 Ctrl+c
Started sing-box.service.
FATAL[0000] decode config at /etc/s-box/sb.json: invalid character ',' looking for beginning of value: row 53, column 28
sing-box.service: Main process exited, code=exited, status=1/FAILURE
sing-box.service: Failed with result 'exit-code'.
sing-box.service: Scheduled restart job, restart counter is at 2.
Stopped sing-box.service.
Started sing-box.service.
FATAL[0000] decode config at /etc/s-box/sb.json: invalid character ',' looking for beginning of value: row 53, column 28
sing-box.service: Main process exited, code=exited, status=1/FAILURE
sing-box.service: Failed with result 'exit-code'.

**Comment by yonggekkk** [comment]
> FATAL[0000] decode config at /etc/s-box/sb.json: invalid character ',' looking for beginning of value: row 53, column 28

你是不是修改过sb.json文件？

**Comment by yzx1208** [comment]
没有任何修改

**Comment by yonggekkk** [comment]
> Sing-box状态：未启动，可尝试选择6重启，依旧如此建议卸载重装Sing-box
> 
> Sing-box启动不起来，以下是日志：
> 
> -0400 2023-11-01 02:07:28 INFO router: downloading geosite database -0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied -0400 2023-11-01 02:07:28 INFO router: downloading geosite database -0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied -0400 2023-11-01 02:07:28 INFO router: downloading geosite database -0400 2023-11-01 02:07:28 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied FATAL[0000] start service: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied sing-box.service: main process exited, code=exited, status=1/FAILURE Unit sing-box.service entered failed state. sing-box.service failed.

已更新修复

**Comment by yonggekkk** [comment]
> 没有任何修改

已更新
