### ISSUE TITLE
自动续期域名失效

### ISSUE THREAD

**Issue by wangyingbo** [yonggekkk/sing-box-yg#100]
麻烦请教甬哥个事情，域名自动续期失效了，最近几次都是第二天连节点时发现连不上，登录server后发现是域名证书过期了，需要再手动续期一下域名才能好。想问下甬哥，这个大概是什么原因呢？如果我想自己开启个crontab来自动续期域名，需要运行哪个命令呢？

**Comment by yonggekkk** [comment]
默认自动续期，80端口占用会续期失败！建议api模式申请可无视端口占用

**Comment by wangyingbo** [comment]
> 默认自动续期，80端口占用会续期失败！建议api模式申请可无视端口占用

好的，谢谢佬！
