### ISSUE TITLE
xoyoqsq@gmail.com

### ISSUE THREAD

**Issue by stevenxoyo** [yonggekkk/sing-box-yg#104]
请问这是怎么回事
请输入数字【0-14】:1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
是否开放端口，关闭防火墙？
1、是，执行 (回车默认)
2、否，跳过！自行处理
请选择【1-2】：1
执行开放端口，关闭防火墙完毕
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
一、开始下载并安装Sing-box正式版内核……请稍等

############################################################################################################################################################### 100.0%
/dev/fd/63: line 227: tar: command not found
mv: cannot stat '/etc/s-box/sing-box-1.9.7-linux-amd64/sing-box': No such file or directory
下载 Sing-box 内核不完整，安装失败，请再运行安装一次

**Comment by yonggekkk** [comment]
tar没装上？换个系统试试
