### ISSUE TITLE
赛风无法获取到IP

### ISSUE THREAD

**Issue by kylo1989** [yonggekkk/sing-box-yg#106]
申请IP中……请稍等……
WARP-plus-Socks5的IP获取失败，尝试换个国家地区吧

使用三台VPS其中一台港区两台美区的，使用赛风获取IP尝试了无数次都无法获取到IP

**Comment by yonggekkk** [comment]
换国家

**Comment by kylo1989** [comment]
> 换国家

换了很多次国家了，基本上所有国家都换了，还是获取不到IP

**Comment by yonggekkk** [comment]
脚本安装过程中有报错吗？

**Comment by kylo1989** [comment]
我是之前的版本直接升级的，刚开始直接在脚本里面选7升级，升级后没有出现14选项，后来复制的GitHub这个一键脚本地址升级的，有了14选项，升级之后重启了VPS，都是这个问题，所有国家我都切换了一遍都获取不到IP，但是warp本地（14选项后的1选项）是可以获取到IP的，因为之前安装脚本里面有节点信息不太方便重装，所以不是新装脚本测试的。如果甬哥有可以保存节点信息的新装方法我也可以新装升级试试看

**Comment by yonggekkk** [comment]
赛风获取IP并不是一定可以成功，但是所有都失败有点意外，你有别的VPS吗？可以试试

**Comment by kylo1989** [comment]
我目前三台VPS，一台香港野草云，两台圣何塞RN，都是这样升级过来的，也都是这样获取不到IP
