### ISSUE TITLE
SB无法安装

### ISSUE THREAD

**Issue by beautygirl1998** [yonggekkk/sing-box-yg#108]
尝试了多次，多不行，vultr debian11新系统，未安装其它程序。

一、开始下载并安装Sing-box正式版内核……请稍等

###################################################################################################################################################### 100.0%

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/etc/s-box/sing-box-1.10.1-linux-amd64v3/sing-box': No such file or directory
下载 Sing-box 内核不完整，安装失败，请再运行安装一次

**Comment by yonggekkk** [comment]
https://github.com/yonggekkk/sing-box-yg/blob/main/version
