### ISSUE TITLE
flow mismatch 

### ISSUE THREAD

**Issue by DFIUGFSguygs** [yonggekkk/sing-box-yg#109]
+0800 2024-10-25 03:20:17 ERROR [1804949437 127ms] inbound/vless[vless-sb]: process connection from xxx.xxx.xxx.xx:16973: flow mismatch: expected xtls-rprx-vision, but got none
+0800 2024-10-25 03:20:17 ERROR [2723890027 127ms] inbound/vless[vless-sb]: process connection from xxx.xxx.xxx.xx:16978: flow mismatch: expected xtls-rprx-vision, but got none很奇怪有时会报错有时又正常
![图片](https://github.com/user-attachments/assets/b4b1c7ab-86ac-45d4-b235-0546a56df1f4)

**Comment by DFIUGFSguygs** [comment]
"bean": {
       "_v": 0,
       "addr": "107.172.xx.xxx",
       "flow": "xtls-rprx-vision",
       "name": "vl-reality-racknerd-52e2fb2",
       "pass": "c602d8ec-7ab9-4542-acb4-6c2e13225bd2",
       "port": 443,
       "stream": {
           "ed_len": 0,
           "insecure": false,
           "mux_s": 0,
           "net": "tcp",
           "pbk": "C4O_xQZBplBytSKCj1Z-wlEPFPsHvJriqJtDe-_ryEI",
           "sec": "tls",
           "sid": "a5e251a9",
           "sni": "www.jetbrains.com",
           "utls": "chrome"
       }
   },
   "gid": 0,
   "id": 0,
   "traffic": {
       "dl": 11151051,
       "ul": 2349281
   },
   "type": "vless",
   "yc": -1
}

**Comment by DFIUGFSguygs** [comment]
hysteria2不会有这样的问题

**Comment by yonggekkk** [comment]
这个没碰到过
