### ISSUE TITLE
手机端tuic5(小火箭正常),电脑端clashverge(clashmeta）error,查看日志有如下提示，不知有无帮助

### ISSUE THREAD

**Issue by ainp** [yonggekkk/sing-box-yg#11]
+0000 2023-11-06 03:01:11 ERROR inbound/vmess[vmess-sb]: process connection from [::1]:45790: bad path: /
+0000 2023-11-06 03:03:31 ERROR inbound/vmess[vmess-sb]: process connection from 167.248.133.125:39654: bad path: /
+0000 2023-11-06 03:03:31 ERROR inbound/vmess[vmess-sb]: process connection from 167.248.133.125:57288: bad path: /
+0000 2023-11-06 03:03:31 ERROR inbound/vmess[vmess-sb]: process connection from 167.248.133.125:45262: bad path: *
+0000 2023-11-06 03:04:03 ERROR inbound/vmess[vmess-sb]: process connection from 167.94.146.60:50548: bad path: /
+0000 2023-11-06 03:04:03 ERROR inbound/tuic[tuic5-sb]: connection failed: handle uni stream: unknown command 4
+0000 2023-11-06 03:04:03 ERROR inbound/vmess[vmess-sb]: process connection from 167.94.146.60:50700: bad path: /
+0000 2023-11-06 03:04:03 ERROR inbound/vmess[vmess-sb]: process connection from 167.94.146.60:53118: bad path: *
+0000 2023-11-06 03:04:24 ERROR inbound/tuic[tuic5-sb]: connection failed: handle uni stream: unknown command 4
+0000 2023-11-06 03:04:56 ERROR inbound/tuic[tuic5-sb]: connection failed: handle uni stream: unknown command 4
+0000 2023-11-06 03:05:28 ERROR inbound/tuic[tuic5-sb]: connection failed: handle uni stream: unknown command 4
+0000 2023-11-06 03:05:39 ERROR inbound/tuic[tuic5-sb]: connection failed: handle uni stream: unknown command 4
+0000 2023-11-06 03:05:49 ERROR inbound/tuic[tuic5-sb]: connection failed: handle uni stream: unknown command 4

**Comment by yonggekkk** [comment]
你改过配置文件？我这测试都正常

**Comment by ainp** [comment]
我没有动过配置文件。用的就是的菜单配置，使用的自己的域名证书

**Comment by ainp** [comment]
我布置在了四个vps上，两个正常，两个不正常，如下图
![image](https://github.com/yonggekkk/sing-box-yg/assets/9693302/ebccd812-80e2-42d8-b8e7-b9a7e6c3fbf1)
![image](https://github.com/yonggekkk/sing-box-yg/assets/9693302/8e545de8-7730-4a96-a7b0-88512693bbd3)
![image](https://github.com/yonggekkk/sing-box-yg/assets/9693302/e835bc1f-24a3-4ed8-aa6d-521b6b023bb6)

**Comment by yonggekkk** [comment]
查看你的clash-meta配置文件，TUIC那段有没有改错

**Comment by ainp** [comment]
![image](https://github.com/yonggekkk/sing-box-yg/assets/9693302/3859727a-9eb6-4459-8f93-d5a115dc9be1)

**Comment by ainp** [comment]
Vmess Tls argo 按照你的指导，修改了。其他都没动，只是节点名字改了

**Comment by ainp** [comment]
不稳定，和vmess 有点像，都是不稳定。有时不能用
