### ISSUE TITLE
ubuntu 24.04.1 LTS使用安装脚本更新sing-box最新测试版本（v1.11.0-alpha.2）提示无法启动

### ISSUE THREAD

**Issue by INetbeep** [yonggekkk/sing-box-yg#110]
操作系统：ubuntu  24.04.1 LTS 
问题：使用脚本（sb->8->2）更新sing-box最新测试版本（v1.11.0-alpha.2）后无法启动
日志如下：
main.main()
        github.com/sagernet/sing-box/cmd/sing-box/main.go:8 +0x1e
sing-box.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sing-box.service: Failed with result 'exit-code'.
sing-box.service: Scheduled restart job, restart counter is at 60.
Started sing-box.service.
+0000 2024-10-30 05:48:59 INFO router: updated default interface eth0, index 2
panic: invalid deprecated note: geosite
goroutine 1 [running]:
github.com/sagernet/sing-box/experimental/deprecated.Note.Impending({{0x154f45d, 0x7}, {0x1557ae2, 0x10}, {0x154e0e7, 0x5}, {0x154e9c5, 0x6}, {0x154f4bf, 0x7}, ...})
        github.com/sagernet/sing-box/experimental/deprecated/constants.go:28 +0x179
github.com/sagernet/sing-box/experimental/deprecated.(*envManager).ReportDeprecated(0xc00004ad60, {{0x154f45d, 0x7}, {0x1557ae2, 0x10}, {0x154e0e7, 0x5}, {0x154e9c5, 0x6}, {0x154f4bf, ...}, ...})
        github.com/sagernet/sing-box/experimental/deprecated/env.go:19 +0x58
github.com/sagernet/sing-box/experimental/deprecated.Report({0x176a030?, 0xc000091540?}, {{0x154f45d, 0x7}, {0x1557ae2, 0x10}, {0x154e0e7, 0x5}, {0x154e9c5, 0x6}, ...})
        github.com/sagernet/sing-box/experimental/deprecated/manager.go:18 +0x59
github.com/sagernet/sing-box/route.(*Router).prepareGeositeDatabase(0xc0000fe848)
        github.com/sagernet/sing-box/route/router_geo_resources.go:92 +0x5b
github.com/sagernet/sing-box/route.(*Router).Start(0xc0000fe848)
        github.com/sagernet/sing-box/route/router.go:487 +0x2eb
github.com/sagernet/sing-box.(*Box).preStart(0xc000151ea0)
        github.com/sagernet/sing-box/box.go:274 +0x7a2
github.com/sagernet/sing-box.(*Box).start(0xc000151ea0)
        github.com/sagernet/sing-box/box.go:278 +0x2a
github.com/sagernet/sing-box.(*Box).Start(0xc000151ea0)
        github.com/sagernet/sing-box/box.go:220 +0x36
main.create()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:160 +0x45d
main.run()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:174 +0x105
main.init.func25(0xc00010de00?, {0x154da70?, 0x4?, 0x154da74?})
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:30 +0x17
github.com/spf13/cobra.(*Command).execute(0x21bccc0, {0xc00007ce80, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x21b7f20)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
        github.com/sagernet/sing-box/cmd/sing-box/main.go:8 +0x1e
sing-box.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
sing-box.service: Failed with result 'exit-code'.

**Comment by INetbeep** [comment]
切换回稳定版本可正常使用。

**Comment by yonggekkk** [comment]
测试版就别认真啦。。。等内核更新
