### ISSUE TITLE
甬哥能不能改一下更新到gitlab默认订阅的name，改成比较简单的 server1 server2 server3 这样

### ISSUE THREAD

**Issue by lclalalalala** [yonggekkk/sing-box-yg#111]
目前这个名字是协议名+uuid啥的。
订阅转换的时候很难匹配规则。
我都手动去gitlab改成 "国家-地区-server1“这样。一更新就给改回去了。
其实日常使用我也不关心是啥协议，名字直白一点标识是哪个VPS来的就行。

**Comment by yonggekkk** [comment]
看得懂脚本可以自己改下脚本
