### ISSUE TITLE
勇哥脚本能添加armv7设备运行吗？

### ISSUE THREAD

**Issue by woshishiq1** [yonggekkk/sing-box-yg#112]
0.0

**Comment by yonggekkk** [comment]
什么设备？

**Comment by woshishiq1** [comment]
bash <(curl -Ls https://raw.githubusercontent.com/woshishiq1/sing-box-yg/main/sb.sh)
目前脚本不支持armv7l架构
小白fork了你仓库修改了aarch64) cpu=arm64为32还是提示这个！不懂还要修改哪！
勇哥我就是提一嘴,不好支持就算了

**Comment by yonggekkk** [comment]
输入uname -m显示什么

**Comment by woshishiq1** [comment]
uname -m
armv7l

**Comment by yonggekkk** [comment]
好了，你用脚本试试

**Comment by woshishiq1** [comment]
可以了，感谢勇哥
