### ISSUE TITLE
运行脚本后报错

### ISSUE THREAD

**Issue by Ericanymouse** [yonggekkk/sing-box-yg#113]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ░██     ░██      ░██ ██ ██         ░██   ░██     ░██   ░██     ░██   ░██  
  ░██   ░██      ░██    ░░██        ░██  ░██      ░██  ░██      ░██  ░██   
   ░██ ░██      ░██                 ░██ ██        ░██ ██        ░██ ██     
     ░██        ░██    ░██ ██       ░██ ██        ░██ ██        ░██ ██    
     ░██         ░██    ░░██        ░██ ░██       ░██ ░██       ░██ ░██   
     ░██          ░██ ██ ██         ░██  ░░██     ░██  ░░██     ░██  ░░██   
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
甬哥Github项目  ：github.com/yonggekkk
甬哥Blogger博客 ：ygkkk.blogspot.com
甬哥YouTube频道 ：www.youtube.com/@ygkkk
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Vless-reality-vision、Vmess-ws(tls)+Argo、Hysteria-2、Tuic-v5 四协议共存脚本
脚本快捷方式：sb
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1. 一键安装 Sing-box
 2. 删除卸载 Sing-box
----------------------------------------------------------------------------------
 3. 变更配置 【双证书TLS/UUID路径/Argo/IP优先/TG通知/Warp/订阅/CDN优选】
 4. 更改主端口/添加多端口跳跃复用
 5. 三通道域名分流
 6. 关闭/重启 Sing-box
 7. 更新 Sing-box-yg 脚本
 8. 更新/切换/指定 Sing-box 内核版本
----------------------------------------------------------------------------------
 9. 刷新并查看节点 【Clash-Meta/SFA+SFI+SFW三合一配置/订阅链接/推送TG通知】
10. 查看 Sing-box 运行日志
11. 一键原版BBR+FQ加速
12. 管理 Acme 申请域名证书
13. 管理 Warp 查看Netflix/ChatGPT解锁情况
14. 添加 WARP-plus-Socks5 代理模式 【本地Warp/多地区Psiphon-VPN】
 0. 退出脚本
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
当前 Sing-box-yg 脚本版本号：v24.10.7
请先选择 1 ，安装 Sing-box-yg 脚本

当前 Sing-box 最新正式版内核：1.10.1
当前 Sing-box 最新测试版内核：1.11.0-alpha.5
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VPS状态如下：
系统:Ubuntu 22.04.4 LTS  内核:6.8.0  处理器:amd64  虚拟化:microsoft  BBR算法:cubic
本地IPV4地址：20.2.166.119   本地IPV6地址：无IPV6
Sing-box状态：未安装
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

bash: line 4871: syntax error near unexpected token `)'
bash: line 4871: ` 1 ) instsllsingbox;;'

**Comment by yonggekkk** [comment]
再试试，我这里正常

**Comment by Ericanymouse** [comment]
不行。。。

**Comment by yonggekkk** [comment]
现在呢

**Comment by Ericanymouse** [comment]
不行...算啦...谢谢大神
