### ISSUE TITLE
甬哥 脚本在更新sing-box 报错 机器cpu类型是AMDV3时 

### ISSUE THREAD

**Issue by gaojiahong** [yonggekkk/sing-box-yg#114]

**Comment by yonggekkk** [comment]
脚本地址如下：
bash <(wget -qO- https://raw.githubusercontent.com/yonggekkk/sing-box-yg/main/sb.sh)
或者
bash <(curl -Ls https://raw.githubusercontent.com/yonggekkk/sing-box-yg/main/sb.sh)

注意：本次更新时，请在SSH输入以上新脚本，选择7进行更新！！！
