### ISSUE TITLE
甲骨文1.10.1更新失败

### ISSUE THREAD

**Issue by liunaiqiu** [yonggekkk/sing-box-yg#115]
甲骨文1.10.1更新失败，提示如下：
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat '/etc/s-box/sing-box-1.10.1-linux-amd64v3/sing-box': No such file or directory

**Comment by yonggekkk** [comment]
脚本地址如下：
bash <(wget -qO- https://raw.githubusercontent.com/yonggekkk/sing-box-yg/main/sb.sh)
或者
bash <(curl -Ls https://raw.githubusercontent.com/yonggekkk/sing-box-yg/main/sb.sh)

注意：本次更新时，请在SSH输入以上新脚本，选择7进行更新！！！
