### ISSUE TITLE
WARP-plus-Socks5 代理模式中的Psiphon-VPN，geosite 模式不起作用

### ISSUE THREAD

**Issue by neohob** [yonggekkk/sing-box-yg#118]
1. WARP-plus-Socks5 代理模式中的Psiphon-VPN，geosite 模式不起作用，用全域名是可以的
2. 非中国地区的geosite没有了。。。
<img width="989" alt="image" src="https://github.com/user-attachments/assets/98862443-3739-4cba-aa89-d74d581cadae">

**Comment by yonggekkk** [comment]
卸载重装下

**Comment by neohob** [comment]
可以了，但是好像不是很稳，ip检测工具ip.sb第一次检测正确后面就不太对了
