### ISSUE TITLE
圣何塞的tuic|hys等不起作用

### ISSUE THREAD

**Issue by lckjcnWq** [yonggekkk/sing-box-yg#119]
涌哥，圣何塞的tuic|hys等不起作用，只有reality起作用了，报错日志如下：
-0500 2024-11-14 20:46:51 ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!
-0500 2024-11-14 20:46:51 ERROR router: failed to initialize geosite: read geosite: code yg_kkk not exists!
-0500 2024-11-14 20:46:51 INFO inbound/vless[vless-sb]: tcp server started at [::]:19276
-0500 2024-11-14 20:46:51 INFO inbound/vmess[vmess-sb]: tcp server started at [::]:2087
-0500 2024-11-14 20:46:51 INFO inbound/hysteria2[hy2-sb]: udp server started at [::]:40093
-0500 2024-11-14 20:46:51 INFO inbound/tuic[tuic5-sb]: udp server started at [::]:19842
-0500 2024-11-14 20:46:51 INFO sing-box started (0.88s)

**Comment by yonggekkk** [comment]
以上不算报错。更换下端口或者重装下试试
