### ISSUE TITLE
支持openwrt

### ISSUE THREAD

**Issue by qy2009** [yonggekkk/sing-box-yg#12]
可以支持下openwrt 嘛？ 我想反向从海外到国内。。。

谢谢啦

**Comment by yonggekkk** [comment]
本来就支持呀！行！下期教程就说下全平台客户端吧

**Comment by qy2009** [comment]
我是 glinet 的x3000, 我装的时候，显示
```
cat: can't open '/etc/issue': No such file or directory
不支持你当前系统，请选择使用Ubuntu,Debian,Centos系统。
```

**Comment by yonggekkk** [comment]
你是说装在openwrt？会缺很多东西！我也没搞docker！脚本主要针对vps的

**Comment by qy2009** [comment]
是啊， 我人在海外，想用singbox 连国内的openwrt. 平时要上银行，视频之类的APP。

**Comment by qy2009** [comment]
要是有docker, 我也可以试一下在docker 里面装。我的openwrt 有docker.

**Comment by yonggekkk** [comment]
脚本高度交互，目前不会考虑docker了
