### ISSUE TITLE
MacOS的Sing-box每次启动时都会弹出提示

### ISSUE THREAD

**Issue by kk8bit** [yonggekkk/sing-box-yg#122]
MacOS的Sing-box每次启动时都会弹出这个提示：
legacy tun address fields is deprecated in sing-box 1.10.0 and will be removed in sing-box 1.12.0, please checkout documentation for migration.

**[提示链接](https://sing-box.sagernet.org/migration/#tun-address-fields-are-merged)**

感谢甬哥辛苦开发，脚本非常好🤝

**Comment by yonggekkk** [comment]
已更新。

**Comment by kk8bit** [comment]
马上去试试，辛苦甬哥
