### ISSUE TITLE
新版本在MacOS的Sing-box客户端报错

### ISSUE THREAD

**Issue by kk8bit** [yonggekkk/sing-box-yg#123]
<img width="252" alt="截屏2024-12-06 下午1 27 31" src="https://github.com/user-attachments/assets/88a88f26-3e26-44fb-86e4-aef5e5233ab0">

The operation couldn’t be completed. ((packet-tunnel) error: create service: create service: outbound not found for rule[0]: dns-out error 0.)

**Comment by yonggekkk** [comment]
> <img alt="截屏2024-12-06 下午1 27 31" width="252" src="https://private-user-images.githubusercontent.com/138471915/393109737-88a88f26-3e26-44fb-86e4-aef5e5233ab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM1MDQsIm5iZiI6MTczMzQ2MzIwNCwicGF0aCI6Ii8xMzg0NzE5MTUvMzkzMTA5NzM3LTg4YTg4ZjI2LTNlMjYtNDRmYi04NmU0LWFlZjVlNTIzM2FiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQwNTMzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzdjMWYzMTBkMGMzYjMzZDhmYjY2MTI2N2RjZmY0Y2RmM2IwMzcyOTIyNWU0N2U1YmFiNTExNTJmYzlmOWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wuMAhh3UA11Xs_kbPpCt5c0t8X3ENY-dqSv81wjAfE4">
> The operation couldn’t be completed. ((packet-tunnel) error: create service: create service: outbound not found for rule[0]: dns-out error 0.)

客户端内核什么版本？升级下

**Comment by yonggekkk** [comment]
的确有问题，我再看看

**Comment by kk8bit** [comment]
一周前在App Store更新的1.10.3

**Comment by yonggekkk** [comment]
再试试

**Comment by kk8bit** [comment]
> 再试试，应该没问题了

还是不行，一样的报错信息

**Comment by yonggekkk** [comment]
> > 再试试，应该没问题了
> 
> 还是不行，一样的报错信息

我用1.11版的

**Comment by hiperioncn** [comment]
我发现问题原因了，现在appstore或Googleplay中的最新版core都是1.10.3，而刚刚我使用脚本安装的server端也是1.10.3,但是使用命令9生成的json文件中，使用了1.11中的特性，例如action，这个是1.11才有的。
我把配置文件导入iPhone上的singbox用不了。现在Mac上安装了一个1.11.0的beta版，可以正常使用。
所以是生成的配置文件问题
