### ISSUE TITLE
Proxy detection failed, please confirm the validity of the proxy IP. If you have any questions, please contact the proxy IP provider!

### ISSUE THREAD

**Issue by sankexin** [yonggekkk/sing-box-yg#124]
IP query channel: ip 123 
How to set ubuntu  to solve this problem?

**Comment by yonggekkk** [comment]
关于proxyip，看我相关概念视频教程

**Comment by sankexin** [comment]
> 关于proxyip，看我相关概念视频教程 https://youtu.be/NaLd-orwFUE

My IP was purchased from a US website, not free proxyip, can use google, but when I filled in my IP and port to the fingerprint browser, it prompted me: Proxy detection failed,  I watched your video and didn't have this part set up

Additionally, curl is also ineffective
curl: (52) Empty reply from server
curl: (97) connection to proxy closed

**Comment by yonggekkk** [comment]
我用的与我了解的不相关

**Comment by sankexin** [comment]
> 我用的与我了解的不相关

I got it, need to filled in local ip：127.0.0.1:port
thank you
