### ISSUE TITLE
使用新的脚本部署后，在mac的sfm下运行报错

### ISSUE THREAD

**Issue by woodychanjm** [yonggekkk/sing-box-yg#125]
报错消息如下：
decode config: route.rules[0].action: json: unknown field "action"

sb信息如下：
当前 Sing-box-yg 脚本最新版：v24.10.7 (已安装)

当前 Sing-box 最新正式版内核：1.10.3 (已安装)

当前 Sing-box 最新测试版内核：1.11.0-beta.11 (可切换)

sfm版本：
1.10.3

**Comment by yonggekkk** [comment]
客户端更新1.11内核

**Comment by woodychanjm** [comment]
更新内核后问题解决，拜谢甬哥
