### ISSUE TITLE
这个版本开始报错了

### ISSUE THREAD

**Issue by yahuudang** [yonggekkk/sing-box-yg#126]
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 164, column 1

**Comment by yonggekkk** [comment]
更新内核了？先保持在1.10内核

**Comment by windy1lee** [comment]
parse error: Invalid string: control characters from U+0000 through U+001F must be escaped at line 164, column 1

**Comment by yonggekkk** [comment]
卸载重装下
