### ISSUE TITLE
域名证书的自动续期功能不起作用！

### ISSUE THREAD

**Issue by gaohua-clamc** [yonggekkk/sing-box-yg#129]
**Thu 19 Dec 2024 01:19:59 PM UTC**
=========================================================================
 1. acme.sh申请letsencrypt ECC证书（支持80端口模式与DNS API模式） 
 2. 查询已申请成功的域名及自动续期时间点 
 3. 手动一键证书续期 
 4. 删除证书并卸载一键ACME证书申请脚本 
 0. 退出 

请输入数字:2
Main_Domainc下显示的域名就是已申请成功的域名证书，Renew下显示对应域名证书的自动续期时间点
Main_Domain                       KeyLength        SAN_Domains        CA                           Created                                Renew
xxx.xxx.xxx                           "ec-256"          no                            LetsEncrypt.org     2024-10-17T15:30:37Z      2024-12-15T15:30:37Z

**Comment by gaohua-clamc** [comment]
我的重点是自动续期为什么不工作？是不是根本就不能自动续期！！！需要手动续期！

**Comment by yonggekkk** [comment]
80端口被占就会自动续失败
