### ISSUE TITLE
圈x无法使用

### ISSUE THREAD

**Issue by hhrensheng** [yonggekkk/sing-box-yg#131]
手机用的是圈x搭配了去广告的分流规则，之前好好的突然就不好用了，版本都是最新的。在其他平台没问题都可以使用
查看日志都是类似的错误
![image](https://github.com/user-attachments/assets/a218f909-a380-4a51-8e73-2e6a137ab52f)

**Comment by yonggekkk** [comment]
XO不支持reality?

**Comment by hhrensheng** [comment]
还真是 Vmess-ws-tls 就行。🙏
