### ISSUE TITLE
订阅或者配置的IP地址没得修改吗？

### ISSUE THREAD

**Issue by breeze303** [yonggekkk/sing-box-yg#134]
我用的是v6它给的是v4的地址，导致我需要手动修改每个订阅协议的地址

**Comment by yonggekkk** [comment]
脚本默认的是双栈VPS，显示V4先。。这个的确比较纠结

**Comment by breeze303** [comment]
> 脚本默认设置的是双栈VPS下，优先显示V4。。这个的确比较纠结

是否可以加入个选项自定义选择配置ip
