### ISSUE TITLE
生成的sing-box配置在sing-box的iOS端无法使用

### ISSUE THREAD

**Issue by xw-yin** [yonggekkk/sing-box-yg#14]
生成的配置在android端没问题但是在iOS端无法启动，配置转换后可以使用，应该是配置有冲突。

**Comment by yonggekkk** [comment]
具体是哪里不一样呢？

**Comment by xw-yin** [comment]
这是你的脚本生成的配置
[sing_box_client.json](https://github.com/yonggekkk/sing-box-yg/files/13304325/sing_box_client.json)
这是转换后的配置
[sing-box_subscribe.json](https://github.com/yonggekkk/sing-box-yg/files/13304326/sing-box_subscribe.json)
不同点有点多，具体是哪里影响我也不知道。

**Comment by yonggekkk** [comment]
了解，等下更新下
