### ISSUE TITLE
vmargo没法用，因为默认443口早就被占用

### ISSUE THREAD

**Issue by kevon2019** [yonggekkk/sing-box-yg#15]
要如何处理？耍节点正常

**Comment by yonggekkk** [comment]
Argo不占用实际端口，13个端口随便换，具体看视频教程说明

**Comment by donkeykangwang10** [comment]
vmess argo节点在小火箭或者passwall均无法连接，argo显示正常，后台日志中显示连接错误。不知道什么原因？

**Comment by yonggekkk** [comment]
> vmess argo节点在小火箭或者passwall均无法连接，argo显示正常，后台日志中显示连接错误。不知道什么原因？

发下错误信息
