### ISSUE TITLE
How to change sni ?

### ISSUE THREAD

**Issue by NoRRt** [yonggekkk/sing-box-yg#16]
Is there a way to change sni in all protocols?

Exm protocol : hysteria2://UUID@domein:Port?peer= domein:Port &insecure=0&sni= (**How to change sni**? )&alpn=h3#6bb0-singbox_hysteria

**Comment by NoRRt** [comment]
3.更改配置（双证书、UUID、Argo域名、IP优先级、TG通知( **Change Sni**）

**Comment by yonggekkk** [comment]
双证书

**Comment by NoRRt** [comment]
Is there SNI change for all protocols? hysteria2 OR tuic-v5 OR ..

**Comment by yonggekkk** [comment]
Independent settings for each protocol

**Comment by NoRRt** [comment]
only for
1: vless-reality protocol, domain name certificate in use: www.yahoo.com.
-------------------
Can SNI be changed? By default 1
There is a Sni. You should change Sni myself. For example, the :
1: vless-reality protocol, domain name certificate in use: www.yahoo.com. By default
2: vless-reality protocol, domain name certificate in use:
Enter : Server Name (Sni): Enter manually

**Comment by yonggekkk** [comment]
https://youtu.be/QwTapeVPeB0
