### ISSUE TITLE
environment: line 1396: iptables: command not found 

### ISSUE THREAD

**Issue by xujiasteven** [yonggekkk/sing-box-yg#18]
HY2 无法添加多端口environment: line 1396: iptables: command not found
                                  environment: line 1397: ip6tables: command not found
<img width="615" alt="截屏2023-11-18 18 51 41" src="https://github.com/yonggekkk/sing-box-yg/assets/100844345/8f5a913a-134d-4d6b-a2da-90c9899bd35e">

**Comment by yonggekkk** [comment]
什么vps？什么系统？

**Comment by xujiasteven** [comment]
亚马逊光帆Debian

**Comment by xujiasteven** [comment]
<img width="575" alt="截屏2023-11-18 19 41 12" src="https://github.com/yonggekkk/sing-box-yg/assets/100844345/68c7b059-daa0-4fd0-8305-c740bff251e2">

**Comment by yonggekkk** [comment]
进tg群@我下

**Comment by xujiasteven** [comment]
> 进tg群@我下

<img width="576" alt="截屏2023-11-18 20 00 44" src="https://github.com/yonggekkk/sing-box-yg/assets/100844345/1c666ac3-867e-4718-8636-f5f3bb905c8a">

**Comment by yonggekkk** [comment]
大多是因为VPS原系统的安装源有问题，导致相关依赖没安装上。。。这里建议新手小白首选ubuntu系统
