### ISSUE TITLE
望大神提供ArgoX的CF固定域名通道支持，warp管理下的方案一提供非全局模式（不屏蔽原端口），方案二提供Socks5-WARP模式的IPV6支持！

### ISSUE THREAD

**Issue by Ceonta** [yonggekkk/sing-box-yg#19]
感激不尽！

**Comment by yonggekkk** [comment]
1：仅从小白角度考虑，固定隧道要域名及配置文件获取，不考虑加了
2：非全局模式可以用xray的出站分流差不多吧，也不用安装WARP脚本了，相关Sing-box-yg与x-ui-yg脚本都已集成此出站分流功能
3：Socks5-WARP模式的IPV6之前默认有，现在没有了，我也奇怪是不是CF官方的问题。。。
