### ISSUE TITLE
SFA/SFI/SFW configuration

### ISSUE THREAD

**Issue by saeidpoko** [yonggekkk/sing-box-yg#21]
Hello
New SFA/SFI/SFW configuration file doesn't work on sing-box android. My app version is 1.7.0, however It works on SFW.
Could you please help me to?

**Comment by yonggekkk** [comment]
![cfb9aa1cb5597134fbd0e0e9c875711](https://github.com/yonggekkk/sing-box-yg/assets/121604513/d02ce722-e577-4e9d-830f-e116eb322f98)

Just updated
