### ISSUE TITLE
甬哥，能否设置默认v4 v6优先出站？没有找到在哪里设置

### ISSUE THREAD

**Issue by ypkin** [yonggekkk/sing-box-yg#4]

**Comment by yonggekkk** [comment]
目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。

**Comment by ypkin** [comment]
> 目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。

电脑上用nekobox检测，默认是v4出站.

![image](https://github.com/yonggekkk/sing-box-yg/assets/59020573/c2324633-21ef-4b05-af20-dc7a1c4a6ef0)

**Comment by yonggekkk** [comment]
> > 目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。
> 
> 电脑上用nekobox检测，默认是v4出站.
> 
> ![image](https://user-images.githubusercontent.com/59020573/280177532-c2324633-21ef-4b05-af20-dc7a1c4a6ef0.png)

选项-路由设置-服务地址策略-选择你要的试试

**Comment by ypkin** [comment]
> > > 目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。
> > 
> > 
> > 电脑上用nekobox检测，默认是v4出站.
> > ![image](https://user-images.githubusercontent.com/59020573/280177532-c2324633-21ef-4b05-af20-dc7a1c4a6ef0.png)
> 
> 选项-路由设置-服务地址策略-选择你要的试试

按你说的办法设置了，似乎没啥变化。

![image](https://github.com/yonggekkk/sing-box-yg/assets/59020573/e5962f6c-671c-4b50-89aa-6b3c26ccb62b)
上面的是按hy2官方方法手动搭建的，设置的v6优先。

**Comment by yonggekkk** [comment]
> > > > 目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。
> > > 
> > > 
> > > 电脑上用nekobox检测，默认是v4出站.
> > > ![image](https://user-images.githubusercontent.com/59020573/280177532-c2324633-21ef-4b05-af20-dc7a1c4a6ef0.png)
> > 
> > 
> > 选项-路由设置-服务地址策略-选择你要的试试
> 
> 按你说的办法设置了，似乎没啥变化。
> 
> ![image](https://user-images.githubusercontent.com/59020573/280179785-e5962f6c-671c-4b50-89aa-6b3c26ccb62b.png) 上面的是按hy2官方方法手动搭建的，设置的v6优先。

到时我看看加上这个设置。。

**Comment by ypkin** [comment]
> > > > > 目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。
> > > > 
> > > > 
> > > > 电脑上用nekobox检测，默认是v4出站.
> > > > ![image](https://user-images.githubusercontent.com/59020573/280177532-c2324633-21ef-4b05-af20-dc7a1c4a6ef0.png)
> > > 
> > > 
> > > 选项-路由设置-服务地址策略-选择你要的试试
> > 
> > 
> > 按你说的办法设置了，似乎没啥变化。
> > ![image](https://user-images.githubusercontent.com/59020573/280179785-e5962f6c-671c-4b50-89aa-6b3c26ccb62b.png) 上面的是按hy2官方方法手动搭建的，设置的v6优先。
> 
> 到时我看看加上这个设置。。


感谢甬哥辛苦无偿的付出！！

**Comment by yonggekkk** [comment]
> > > > > > 目前是服务端系统默认设置，全局双栈肯定V6优选吧，有些客户端可以设置V4还是V6优选的。。
> > > > > 
> > > > > 
> > > > > 电脑上用nekobox检测，默认是v4出站.
> > > > > ![image](https://user-images.githubusercontent.com/59020573/280177532-c2324633-21ef-4b05-af20-dc7a1c4a6ef0.png)
> > > > 
> > > > 
> > > > 选项-路由设置-服务地址策略-选择你要的试试
> > > 
> > > 
> > > 按你说的办法设置了，似乎没啥变化。
> > > ![image](https://user-images.githubusercontent.com/59020573/280179785-e5962f6c-671c-4b50-89aa-6b3c26ccb62b.png) 上面的是按hy2官方方法手动搭建的，设置的v6优先。
> > 
> > 
> > 到时我看看加上这个设置。。
> 
> 感谢甬哥辛苦无偿的付出！！

已更新支持，老版本需要卸载重装
