### ISSUE TITLE
Cloudflared Argo 隧道启动失败

### ISSUE THREAD

**Issue by xiaosahuogui** [yonggekkk/sing-box-yg#5]
![微信截图_20231103115006](https://github.com/yonggekkk/sing-box-yg/assets/36768240/ac39735e-b4bf-43b5-902f-1ef386228d9d)

**Comment by yonggekkk** [comment]
目前CF可能宕机了。。等吧

**Comment by yonggekkk** [comment]
Argo失效不影响其他四个协议！
保持vmess的tls关闭！到时可能自己会活过来

**Comment by yonggekkk** [comment]
现在argo临时隊道节点已恢复！

**Comment by donkeykangwang10** [comment]
我关闭了tls，然后重置Argo域名，显示域名成功，但是Argo不能运行，显示如下：

Sing-box节点关键信息、已分流域名情况如下：

🚀【   Vmess-ws    】端口:8080   证书形式:TLS关闭   Argo状态:关闭中

**Comment by yonggekkk** [comment]
> 我关闭了tls，然后重置Argo域名，显示域名成功，但是Argo不能运行，显示如下：
> 
> Sing-box节点关键信息、已分流域名情况如下：
> 
> 🚀【 Vmess-ws 】端口:8080 证书形式:TLS关闭 Argo状态:关闭中

切换或者重置后，可能要等1分钟，你再进入应该会显示运行中，你可以看下

**Comment by donkeykangwang10** [comment]
> > 我关闭了tls，然后重置Argo域名，显示域名成功，但是Argo不能运行，显示如下：
> > Sing-box节点关键信息、已分流域名情况如下：
> > 🚀【 Vmess-ws 】端口:8080 证书形式:TLS关闭 Argo状态:关闭中
> 
> 切换或者重置后，可能要等1分钟，你再进入应该会显示运行中，你可以看下

我再次重置，显示如下，应该是重置成功了。过了一分钟后进入查看仍然显示Argo状态：关闭中。
Sing-box配置变更选择如下:
1：reality证书更换、其他协议自签证书与域名证书相互切换 (调整证书验证或者TLS)
2：变更全协议uuid (密码)
3：重置申请Argo隧道临时域名
4：切换本地IPV4、IPV6出站优先级
5：设置Telegram机器人通知功能
0：返回上层
请选择【0-5】：3
第1次刷新验证Cloudflared Argo隧道域名有效性，请稍等……
Argo隧道申请成功且验证有效，域名：suffered-contemporary-stopping-.......
root@instance-20231107-1406:~#

**Comment by yonggekkk** [comment]
> > > 我关闭了tls，然后重置Argo域名，显示域名成功，但是Argo不能运行，显示如下：
> > > Sing-box节点关键信息、已分流域名情况如下：
> > > 🚀【 Vmess-ws 】端口:8080 证书形式:TLS关闭 Argo状态:关闭中
> > 
> > 
> > 切换或者重置后，可能要等1分钟，你再进入应该会显示运行中，你可以看下
> 
> 我再次重置，显示如下，应该是重置成功了。过了一分钟后进入查看仍然显示Argo状态：关闭中。 Sing-box配置变更选择如下: 1：reality证书更换、其他协议自签证书与域名证书相互切换 (调整证书验证或者TLS) 2：变更全协议uuid (密码) 3：重置申请Argo隧道临时域名 4：切换本地IPV4、IPV6出站优先级 5：设置Telegram机器人通知功能 0：返回上层 请选择【0-5】：3 第1次刷新验证Cloudflared Argo隧道域名有效性，请稍等…… Argo隧道申请成功且验证有效，域名：suffered-contemporary-stopping-....... root@instance-20231107-1406:~#

确保你vmess-ws的节点正常。多等会就好，

**Comment by yonggekkk** [comment]
我查看下有没有BUG

**Comment by donkeykangwang10** [comment]
小火箭里Hy2节点有效，Vmess节点无论有无argo，都无法连接。不知道argo无法运行是否和节点无法连接有关。yongge辛苦了

**Comment by yonggekkk** [comment]
> > > 我关闭了tls，然后重置Argo域名，显示域名成功，但是Argo不能运行，显示如下：
> > > Sing-box节点关键信息、已分流域名情况如下：
> > > 🚀【 Vmess-ws 】端口:8080 证书形式:TLS关闭 Argo状态:关闭中
> > 
> > 
> > 切换或者重置后，可能要等1分钟，你再进入应该会显示运行中，你可以看下
> 
> 我再次重置，显示如下，应该是重置成功了。过了一分钟后进入查看仍然显示Argo状态：关闭中。 Sing-box配置变更选择如下: 1：reality证书更换、其他协议自签证书与域名证书相互切换 (调整证书验证或者TLS) 2：变更全协议uuid (密码) 3：重置申请Argo隧道临时域名 4：切换本地IPV4、IPV6出站优先级 5：设置Telegram机器人通知功能 0：返回上层 请选择【0-5】：3 第1次刷新验证Cloudflared Argo隧道域名有效性，请稍等…… Argo隧道申请成功且验证有效，域名：suffered-contemporary-stopping-....... root@instance-20231107-1406:~#

脚本更新了下，你选7更新下，应该就正常了

**Comment by donkeykangwang10** [comment]
谢谢甬哥，现在可以了。
