### ISSUE TITLE
Multi users with different uuid

### ISSUE THREAD

**Issue by Mehdisharbaf** [yonggekkk/sing-box-yg#6]
Hello from Iran
please make it possible to add users with different uuid.
Thanks.

**Comment by yonggekkk** [comment]
There are currently no plans to add multi-user functionality. Tuic and hy2 support multiple ports. How about assigning each port to each user?

**Comment by Mehdisharbaf** [comment]
Yes, it is possible, but 443 port works more easily in Iran.

**Comment by yonggekkk** [comment]
There is actually no problem if the same UUID is used by multiple people.
