### ISSUE TITLE
申请脚本

### ISSUE THREAD

**Issue by sunlewuyou** [yonggekkk/sing-box-yg#65]
甬哥，用了第三方sing-box增加了端口跳跃的功能，可以发脚本源码给我吗？学习自用，然后请教下脚本中最终生成的分流规则用上去还不错，以后会更新吗，可以在脚本中写下分流配置的注解吗？好想自己也能写出来精确的分流规则不用老是拿别人现成的用。谢谢！

**Comment by soso636** [comment]
可以发我一份么，不加密的，学习一下，谢谢勇哥fxiang319@gmail。com

**Comment by yonggekkk** [comment]
> 可以发我一份么，不加密的，学习一下，谢谢勇哥fxiang319@gmail。com

下个更新就不加密了。
