### ISSUE TITLE
装完以后输入10查看日志提示

### ISSUE THREAD

**Issue by alipapabi** [yonggekkk/sing-box-yg#9]
sing-box.service failed.
Stopped sing-box.service.
Started sing-box.service.
+0800 2023-11-04 23:50:30 WARN router: geosite database not exists: geosite.db
+0800 2023-11-04 23:50:30 INFO router: downloading geosite database
+0800 2023-11-04 23:50:30 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
+0800 2023-11-04 23:50:30 INFO router: downloading geosite database
+0800 2023-11-04 23:50:30 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied
+0800 2023-11-04 23:50:30 INFO router: downloading geosite database
+0800 2023-11-04 23:50:30 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied

**Comment by yonggekkk** [comment]
在我tg群吗？@我下

**Comment by xoyoq** [comment]
我也一样，这个文件下载不了，我去网站自己下载了，但是不知道放到VPS哪个目录去

**Comment by yonggekkk** [comment]
> 我也一样，这个文件下载不了，我去网站自己下载了，但是不知道放到VPS哪个目录去

在我TG群吗？在的话@下，我加你

**Comment by yonggekkk** [comment]
> sing-box.service failed. Stopped sing-box.service. Started sing-box.service. +0800 2023-11-04 23:50:30 WARN router: geosite database not exists: geosite.db +0800 2023-11-04 23:50:30 INFO router: downloading geosite database +0800 2023-11-04 23:50:30 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied +0800 2023-11-04 23:50:30 INFO router: downloading geosite database +0800 2023-11-04 23:50:30 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied +0800 2023-11-04 23:50:30 INFO router: downloading geosite database +0800 2023-11-04 23:50:30 ERROR router: download geosite database: open output file: https://github.com/soffchen/sing-geosite/releases/latest/download/geosite.db: open geosite.db: permission denied

已修复
